// const swaggerDocument = {
//     openapi: '3.0.1',
//     info: {
//         version: '1.0.0',
//         title: 'APIs Document',
//         description: 'Workout API description',
//         termsOfService: '',
//         contact: {
//             name: 'Kade',
//             email: 'kadeshikaal@gmail.com'
//         }
//     }
// }

// module.exports = swaggerDocument;

const swaggerAutogen = require('swagger-autogen')({autoHeader: true})
// const authRouter = require('src/routes/auth/auth.router');
// const userRouter = require('src/routes/users/users.router');
// const workoutRouter = require('src/routes/workouts/workouts.router');
// const exerciseRouter = require('src/routes/exercises/exercises.router');

const doc = {
    info: {
        version: "1.0.0",
        title: "My API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "User",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        apiKeyAuth:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {
        Parents: {
            father: "Simon Doe",
            mother: "Marie Doe"
        },
        User: {
            name: "Jhon Doe",
            age: 29,
            parents: {
                $ref: '#/definitions/Parents'
            },
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        AddUser: {
            $name: "Jhon Doe",
            $age: 29,
            about: ""
        }
    }
}

const outputFile = 'src/swagger_output.json'
const endpointsFiles = ['src/routes/auth/auth.router', 'src/routes/users/users.router', 'src/routes/workouts/workouts.router', 'src/routes/exercises/exercises.router']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./server.js')           // Your project's root file
})